# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish package

on:
    release:
        types: created

jobs:
    Publish:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            id-token: write

        steps:
            - name: Setup Action
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "22"
                  registry-url: https://npm.pkg.github.com/

            - name: Setup PNPM
              uses: pnpm/action-setup@v2
              with:
                  version: "latest"

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Build
              run: pnpm run build

            - name: Publish
              run: pnpm publish --provenance --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
